ALTER DATABASE `INVENTORY_MANAGEMENT` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `INVENTORY_MANAGEMENT`;

  CREATE TABLE IF NOT EXISTS `ADMIN_USER` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NULL,
    MOBILE VARCHAR(20) NOT NULL,
    USERNAME VARCHAR(200) NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    ROLE VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(200) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_BY VARCHAR(200) NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    ACTIVE VARCHAR(1) NOT NULL,
    DELETED VARCHAR(1) NOT NULL,
    PRIMARY KEY (`ID`)
  ) ENGINE=INNODB;

  CREATE TABLE IF NOT EXISTS `CATEGORY` (
    `ID` BIGINT NOT NULL,
     CATEGORY_NAME VARCHAR(20) NULL DEFAULT NULL,
     CREATED_BY VARCHAR(30) NOT NULL,
     CREATED_DATE DATETIME NOT NULL,
     UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
     UPDATED_DATE DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`ID`)
    ) ENGINE=INNODB;


  CREATE TABLE IF NOT EXISTS `PRICING` (
    `ID` BIGINT NOT NULL,
     PRICING_NAME VARCHAR(20) NULL DEFAULT NULL,
     DISCOUNT_PERCENTAGE DECIMAL(10,0) NULL DEFAULT NULL,
     PRICING_EFFECTIVE_DATE DATE NULL DEFAULT NULL,
     PRICING_EXPIRE_DATE DATE NULL DEFAULT NULL,
     CREATED_BY VARCHAR(30) NOT NULL,
     CREATED_DATE DATETIME NOT NULL,
     UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
     UPDATED_DATE DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`ID`)
    ) ENGINE=INNODB;


  CREATE TABLE IF NOT EXISTS `PRODUCT` (
    `ID` BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(20) NULL DEFAULT NULL,
    PRODUCT_IS_SERVICE TINYINT(1) NULL DEFAULT NULL,
    PRODUCT_BUYING_PRICE DOUBLE NULL DEFAULT NULL,
    PRODUCT_SELLING_PRICE DOUBLE NULL DEFAULT NULL,
    CATEGORY_ID INT(11) NULL DEFAULT NULL,
    CREATED_BY VARCHAR(30) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
    UPDATED_DATE DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`ID`))
    ENGINE = INNODB;


  CREATE TABLE IF NOT EXISTS `SUPPLIER` (
    `ID` BIGINT NOT NULL,
     SUPPLIER_NAME VARCHAR(20) NULL DEFAULT NULL,
     SUPPLIER_CONTACT DECIMAL(10,0) NULL DEFAULT NULL,
     SUPPLIER_COMPANY VARCHAR(30) NULL DEFAULT NULL,
     CREATED_BY VARCHAR(30) NOT NULL,
     CREATED_DATE DATETIME NOT NULL,
     UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
     UPDATED_DATE DATETIME NULL DEFAULT NULL,
     PRIMARY KEY (`ID`))
     ENGINE = INNODB;


  CREATE TABLE IF NOT EXISTS `STOCK` (
    `REF_ID` BIGINT NOT NULL,
     STOCK_ID INT(11) NULL DEFAULT NULL,
     SUPPLIER_ID INT(11) NULL DEFAULT NULL,
     PRODUCT_ID INT(11) NULL DEFAULT NULL,
     CATEGORY_ID INT(11) NULL DEFAULT NULL,
     QUANTITY INT(11) NULL DEFAULT NULL,
     DATE_STOCK DATE NULL DEFAULT NULL,
     CREATED_BY VARCHAR(30) NOT NULL,
     CREATED_DATE DATETIME NOT NULL,
     UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
     UPDATED_DATE DATETIME NULL DEFAULT NULL,
     BRANCH_ID VARCHAR(45) NULL,
    PRIMARY KEY (`REF_ID`),
    INDEX `PRODUCT_ID` (`PRODUCT_ID` ASC),
    INDEX `SUPPLIER_ID` (`SUPPLIER_ID` ASC),
    INDEX `CATEGORY_ID` (`CATEGORY_ID` ASC))
    ENGINE = INNODB;

  CREATE TABLE IF NOT EXISTS `PRODUCT_PRICING` (
    `REF_ID` BIGINT NOT NULL,
    `PRICING_PRICING_ID` INT(11) NOT NULL,
    `PRODUCT_PRODUCT_ID` INT(11) NOT NULL,
    PRIMARY KEY (`REF_ID`))
    ENGINE=INNODB;

  CREATE TABLE IF NOT EXISTS `USER` (
    `USER_ID` BIGINT NOT NULL,
    `USERNAME` VARCHAR(50) NOT NULL,
    `USER_FIRST_NAME` VARCHAR(45) NOT NULL,
    `USER_LAST_NAME` VARCHAR(45) NOT NULL,
    `USER_CONTACT_NUMBER` DECIMAL(11) NOT NULL,
    `USER_EMAIL` VARCHAR(45) NOT NULL,
    `USER_ADDRESS` VARCHAR(105) NOT NULL,
     CREATED_BY VARCHAR(30) NOT NULL,
     CREATED_DATE DATETIME NOT NULL,
     UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
     UPDATED_DATE DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`USER_ID`))
    ENGINE = INNODB;


  CREATE TABLE IF NOT EXISTS `ROLE` (
    `ROLE_ID` BIGINT NOT NULL,
    `ROLE_NAME` VARCHAR(45) NULL,
     CREATED_BY VARCHAR(30) NOT NULL,
     CREATED_DATE DATETIME NOT NULL,
     UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
     UPDATED_DATE DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`ROLE_ID`))
    ENGINE = INNODB;

    CREATE TABLE IF NOT EXISTS `PERMISSION` (
      `ID` BIGINT NOT NULL,
      PERMISSION_NAME VARCHAR(45) NULL,
      PRIMARY KEY (`ID`))
      ENGINE = InnoDB;

    CREATE TABLE IF NOT EXISTS `INVOICE` (
       ID BIGINT NOT NULL,
       PRODUCT_ID BIGINT NULL,
       PRODUCT_NAME VARCHAR(45) NULL,
       QUANTITY DOUBLE NULL,
       LINE_TOTAL DOUBLE NULL,
       TOTAL DOUBLE NULL,
       CREATED_BY VARCHAR(30) NOT NULL,
       CREATED_DATE DATETIME NOT NULL,
       UPDATED_BY VARCHAR(30) NULL DEFAULT NULL,
       UPDATED_DATE DATETIME NULL DEFAULT NULL,
      PRIMARY KEY (`ID`))
      ENGINE = InnoDB;