USE `INVENTORY`;

CREATE OR REPLACE VIEW `PRODUCT_FEATURES_VIEW` AS
SELECT
   P.ID AS ID,
   B.ID AS BRAND_ID,
   B.BRAND_NAME AS BRAND,
   C.ID AS CRUSHER_ID,
   C.CRUSHER AS CRUSHER,
   C.LOCATION AS CRUSHER_LOCATION,
   W.ID AS WEIGHT_ID,
   W.WEIGHT AS WEIGHT,
   G.ID AS GRADE_ID,
   G.GRADE AS GRADE,
   Q.ID AS QUALITY_ID,
   Q.QUALITY AS QUALITY,
   T.ID AS TYPE_ID,
   T.TYPE AS TYPE,
   U.ID AS UNIT_ID,
   U.UNIT_NAME AS UNIT_NAME,
   U.UNIT_CODE AS UNIT_CODE,
   M.ID AS MATERIAL_ID,
   M.MATERIAL AS MATERIAL,
   CLR.ID AS COLOR_ID,
   CLR.COLOR AS COLOR,
   PRV.SALE_RATE AS SALE_RATE,
   PRV.MRP_RATE AS MRP_RATE
FROM `PRODUCTS` P
    LEFT JOIN `BRAND` B
         ON (P.BRAND_ID = B.ID)
    LEFT JOIN `CRUSHER` C
         ON (P.CRUSHER_ID = C.ID)
    LEFT JOIN `WEIGHT` W
         ON (P.WEIGHT_ID = W.ID)
    LEFT JOIN `GRADE` G
         ON (P.GRADE_ID = G.ID)
    LEFT JOIN `QUALITY` Q
         ON (P.QUALITY_ID =Q.ID)
    LEFT JOIN `TYPE` T
         ON (P.TYPE_ID = T.ID)
    LEFT JOIN `UNITS` U
         ON (P.UNIT_ID = U.ID)
    LEFT JOIN `MATERIALS` M
         ON (P.MATERIAL_ID = M.ID)
    LEFT JOIN `COLOR` CLR
         ON (P.COLOR_ID = CLR.ID)
    LEFT JOIN `PROD_VENDOR` PRV
             ON (P.ID = PRV.PROD_ID) WHERE PRV.DEFAULT_VENDOR = 'T' AND PRV.DELETED = 'F';