USE `UNITEDSUPPLIES`;

ALTER TABLE `PRODUCTS` MODIFY `UNIT_ID` BIGINT;

ALTER TABLE `PROD_VENDOR` ADD `ACTUAL_RATE` DECIMAL (10,2) ;

CREATE TABLE PRODUCT_CHARGE_HISTORY (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `PROD_ID` BIGINT NOT NULL,
  `VENDOR_ID` BIGINT NOT NULL,
  MRP_RATE DECIMAL(10,2) NOT NULL,
  SALE_RATE DECIMAL(10,2) NOT NULL,
  ACTUAL_RATE DECIMAL (10,2) NOT NULL,
  PIN_CODE VARCHAR(6) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=INNODB  DEFAULT CHARSET=UTF8;

ALTER TABLE `RAZORPAY_PAYMENT` ADD `ORDER_NO` VARCHAR(50) NOT NULL ;

