ALTER DATABASE `UNITEDSUPPLIES` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `UNITEDSUPPLIES`;

CREATE TABLE IF NOT EXISTS `ADMIN_USERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  FULL_NAME VARCHAR(200) NOT NULL,
  EMAIL VARCHAR(200) NOT NULL,
  MOBILE VARCHAR(20) NOT NULL,
  USERNAME VARCHAR(200) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  ROLE VARCHAR(1) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_ADM_USR_I` ON `ADMIN_USERS` (USERNAME, DELETED);

CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  FULL_NAME VARCHAR(200) NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  MOBILE VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(200) NULL,
  ROLE VARCHAR(1) NOT NULL,
  IMAGE_PATH VARCHAR(300) NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  RESET_PWD VARCHAR(1) NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_USR_I` ON `USERS` (FULL_NAME, DELETED);

CREATE TABLE IF NOT EXISTS `USER_OTP` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  OTP VARCHAR(200) NOT NULL,
  MOBILE VARCHAR(20) NOT NULL,
  OTP_TYPE VARCHAR(1) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_USR_OTP` ON `USER_OTP` (USER_ID,OTP, MOBILE);

CREATE TABLE IF NOT EXISTS `CATEGORY` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  CATEGORY_NAME VARCHAR(200) NOT NULL,
  PARENT_CATEGORY BIGINT NULL,
  IMAGE_PATH VARCHAR(200) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_CAT_I` ON `CATEGORY` (CATEGORY_NAME, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `BRAND` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  BRAND_NAME VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_BRD_I` ON `BRAND` (BRAND_NAME, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `QUALITY` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  QUALITY VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_QTY_I` ON `QUALITY` (QUALITY, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `GRADE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  GRADE VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_GRD_I` ON `GRADE` (GRADE, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `TYPE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_TYP_I` ON `TYPE` (TYPE, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `SIZE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `SIZE` VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_SIZE_I` ON `SIZE` (SIZE, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `CRUSHER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CRUSHER` VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  LOCATION VARCHAR(100) NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_CRUSH_I` ON `CRUSHER` (CRUSHER, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `UNIT_MAPPING` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  UNIT_ID BIGINT NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_UNIT_M_I` ON `UNIT_MAPPING` (UNIT_ID, CATEGORY_ID, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `UNITS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  UNIT_NAME VARCHAR(100) NOT NULL,
  UNIT_CODE VARCHAR(10) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_UNITS_I` ON `UNITS` (UNIT_NAME, UNIT_CODE, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `WEIGHT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `WEIGHT` VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_WEIGT_I` ON `WEIGHT` (WEIGHT, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `MATERIALS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  MATERIAL VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_MRL_I` ON `MATERIALS` (MATERIAL, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `SPECIFICATION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  SPECIFICATION VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_SPE_I` ON `SPECIFICATION` (SPECIFICATION, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `COLOR` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  COLOR VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_COLOR_I` ON `COLOR` (COLOR, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `PROMOTION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PROMOTION_NAME VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(2000) NULL,
  IMAGE_PATH VARCHAR(200) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_PROMO_I` ON `PROMOTION` (PROMOTION_NAME, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `PRODUCTS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PRODUCT_CODE VARCHAR(20) NOT NULL,
  PRODUCT_NAME VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(2000) NULL,
  DELIVERY_BY TINYINT NOT NULL,
  IMAGE_PATH VARCHAR(200) NOT NULL,
  IMAGE_PATH_OPT1 VARCHAR(200) NULL,
  IMAGE_PATH_OPT2 VARCHAR(200) NULL,
  IMAGE_PATH_OPT3 VARCHAR(200) NULL,
  PARENT_CATEGORY BIGINT NOT NULL,
  SUB_CATEGORY BIGINT NULL,
  BRAND_ID BIGINT NULL,
  QUALITY_ID BIGINT NULL,
  GRADE_ID BIGINT NULL,
  TYPE_ID BIGINT NULL,
  CRUSHER_ID BIGINT NULL,
  UNIT_ID VARCHAR(100) NOT NULL,
  WEIGHT_ID BIGINT NULL,
  MATERIAL_ID BIGINT NULL,
  COLOR_ID BIGINT NULL,
  `SIZE` VARCHAR(200) NULL,
  SPECIFICATION VARCHAR(200) NULL,
  HSN_CODE VARCHAR(20) NULL,
  RATE_OF_CGST FLOAT NULL,
  RATE_OF_SGST FLOAT NULL,
  RATE_OF_IGST FLOAT NULL,
  MIN_ORDER_QTY SMALLINT NOT NULL,
  MAX_ORDER_QTY SMALLINT NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  IN_STOCK VARCHAR(1) NOT NULL,
  TAX_INCLUSIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_PROD_I` ON `PRODUCTS` (PRODUCT_NAME, DELETED);

CREATE TABLE IF NOT EXISTS `PROD_VENDOR` (
   `ID` BIGINT NOT NULL AUTO_INCREMENT,
   `PROD_ID` BIGINT NOT NULL,
   `VENDOR_ID` BIGINT NOT NULL,
   MRP_RATE DECIMAL(10,2) NOT NULL,
   SALE_RATE DECIMAL(10,2) NOT NULL,
   PIN_CODE VARCHAR(6) NOT NULL,
  `DEFAULT_VENDOR` VARCHAR(1) NOT NULL,
  `DISABLED` VARCHAR(1) NOT NULL,
   CREATED_BY VARCHAR(200) NOT NULL,
   CREATED_DATE DATETIME NOT NULL,
   UPDATED_BY VARCHAR(200) NOT NULL,
   UPDATED_DATE DATETIME NOT NULL,
   DELETED VARCHAR(1) NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_PROD_VEND_I` ON `PROD_VENDOR` (PROD_ID, VENDOR_ID, DELETED);

CREATE TABLE IF NOT EXISTS `TRANSPORT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY INT NOT NULL,
  DISTANCE INT NULL,
  CHARGES DECIMAL(10,2) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_TRANS_I` ON `TRANSPORT` (PRODUCT_ID , DELETED);

CREATE TABLE IF NOT EXISTS `LOADING_CHARGES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY INT NOT NULL,
  CHARGES DECIMAL(10,2) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_LOAD_I` ON `LOADING_CHARGES` (PRODUCT_ID , DELETED);

CREATE TABLE IF NOT EXISTS `USER_CART` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PRODUCT_ID BIGINT NOT NULL,
  PROD_VENDOR_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  QUANTITY INT NULL,
  UNIT_ID BIGINT NULL,
  TRANS_CHARGES DECIMAL(10,0) NOT NULL,
  LOADING_CHARGES DECIMAL(10,0) NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_CART_I` ON `USER_CART` (PRODUCT_ID , USER_ID);

CREATE TABLE IF NOT EXISTS `ORDERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  ORDER_REF BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  ORDER_DATE DATETIME NOT NULL,
  ORDER_NO VARCHAR(20) NOT NULL,
  ORDER_SUBTOTAL DECIMAL(10,2) NOT NULL,
  TRANS_CHARGES DECIMAL(10,2) NOT NULL,
  LOAD_CHARGES DECIMAL(10,2) NOT NULL,
  SERV_CHARGES DECIMAL(10,2) NOT NULL,
  ORDER_TOTAL DECIMAL(10,2) NOT NULL,
  DEL_ADDRESS_ID BIGINT NOT NULL,
  BILL_ADDRESS_ID BIGINT NOT NULL,
  PAYMENT_TYPE VARCHAR(20) NOT NULL,
  PAYMENT_STATUS VARCHAR(1) NOT NULL,
  PAID_AMOUNT DECIMAL(10,0) NOT NULL,
  PAYMENT_PROVIDER VARCHAR(1) NOT NULL,
  GW_ORDER_ID VARCHAR(50) NULL,
  IS_READ VARCHAR(1) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
  CUST_SERV_INVOICE_NO VARCHAR(50) NULL,
  CUST_SERV_INVOICE_DATE DATETIME NULL,
  CHANGE_LOG VARCHAR(500) NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_ORD_I` ON `ORDERS` (USER_ID, DELETED);

CREATE TABLE `PROD_ORDERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  ORDER_REF BIGINT NOT NULL,
  FULFILLMENT_ID BIGINT NOT NULL,
  PROD_ID BIGINT NOT NULL,
  PROD_VEND_ID BIGINT NOT NULL,
  INIT_PROD_VEND_ID BIGINT NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  FULFILLMENT_STATUS VARCHAR(1) NOT NULL,
  PRO_QTY INT NOT NULL,
  PRO_SALE_RATE DECIMAL(10,2) NOT NULL,
  INIT_PRO_SALE_RATE DECIMAL(10,2) NOT NULL,
  TRANS_CHARGES DECIMAL(10,2) NOT NULL,
  INIT_TRANS_CHARGES DECIMAL(10,2) NOT NULL,
  LOAD_CHARGES DECIMAL(10,2) NOT NULL,
  HSN_CODE VARCHAR(20) NULL,
  RATE_OF_CGST FLOAT NULL,
  RATE_OF_SGST FLOAT NULL,
  RATE_OF_IGST FLOAT NULL,
  TAX_INCLUSIVE VARCHAR(1) NOT NULL,
  PRODUCT_CODE VARCHAR(20) NOT NULL,
  PRODUCT_NAME VARCHAR(200) NOT NULL,
  VENDOR_CODE VARCHAR(10) NOT NULL,
  VENDOR_NAME VARCHAR(200) NOT NULL,
  PIN_CODE VARCHAR(10) NOT NULL,
  GST_NO VARCHAR(25) NOT NULL,
  PAN_NO VARCHAR(20) NULL,
  DESCRIPTION VARCHAR(2000) NULL,
  DELIVERY_BY TINYINT NOT NULL,
  IMAGE_PATH VARCHAR(200) NOT NULL,
  IMAGE_PATH_OPT1 VARCHAR(200) NULL,
  IMAGE_PATH_OPT2 VARCHAR(200) NULL,
  IMAGE_PATH_OPT3 VARCHAR(200) NULL,
  PARENT_CATEGORY_NAME VARCHAR(200) NOT NULL,
  SUB_CATEGORY_NAME VARCHAR(200) NULL,
  BRAND_NAME VARCHAR(200) NULL,
  QUALITY_NAME VARCHAR(200) NULL,
  GRADE_NAME VARCHAR(200) NULL,
  TYPE_NAME VARCHAR(200) NULL,
  CRUSHER_NAME VARCHAR(200) NULL,
  UNIT_ID BIGINT NOT NULL,
  UNIT_CODE VARCHAR(200) NOT NULL,
  UNIT_NAME VARCHAR(200) NOT NULL,
  WEIGHT_NAME VARCHAR(200) NULL,
  MATERIAL_NAME VARCHAR(200) NULL,
  COLOR_NAME VARCHAR(200) NULL,
  `SIZE` VARCHAR(200) NULL,
  SPECIFICATION VARCHAR(200) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_PRD_ORD_I` ON `PROD_ORDERS` (ORDER_REF, PROD_ID);

CREATE TABLE `ORDER_FULFILLMENT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  FULFILLMENT_REF VARCHAR(3) NOT NULL,
  PRODUCT_INVOICE_NO VARCHAR(50) NULL,
  PRODUCT_INVOICE_DATE DATETIME NULL,
  SELL_SERV_INVOICE_NO VARCHAR(50) NULL,
  SELL_SERV_INVOICE_DATE DATETIME NULL,
  SELL_SERV_INVOICE_AMOUNT VARCHAR(20) NULL,
  ORDER_REF BIGINT NOT NULL,
  PROD_VENDOR_ID BIGINT NULL,
  VENDOR_CODE VARCHAR(10) NULL,
  VENDOR_NAME VARCHAR(200) NULL,
  COMPANY_NAME VARCHAR(100) NULL,
  ADDRESS VARCHAR(400) NULL,
  CITY VARCHAR(20) NULL,
  PIN_CODE VARCHAR(10) NULL,
  GST_NO VARCHAR(25) NULL,
  PAN_NO VARCHAR(20) NULL,
  ORDER_SUBTOTAL DECIMAL(10,2) NOT NULL,
  TRANS_CHARGES DECIMAL(10,2) NOT NULL,
  LOAD_CHARGES DECIMAL(10,2) NOT NULL,
  SERV_CHARGES DECIMAL(10,2) NOT NULL,
  ORDER_TOTAL DECIMAL(10,2) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_ORD_FUL_I` ON `ORDER_FULFILLMENT` (FULFILLMENT_REF, ORDER_REF);

CREATE TABLE `ADDRESS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `REF` BIGINT NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(200) NOT NULL,
  `MOBILE_NO` VARCHAR(50) NOT NULL,
  `ADDRESS` VARCHAR(500) NOT NULL,
  `POSTAL_CODE` VARCHAR(10) NOT NULL,
  `CITY` VARCHAR(50) NOT NULL,
  `TYPE` VARCHAR(1) NULL,
  `CATEGORY` VARCHAR(1) NOT NULL,
  `GST_NO` VARCHAR(25) NULL,
  `IS_DEFAULT` VARCHAR(1) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_ADDR` ON `ADDRESS` (USER_ID, MOBILE_NO, DELETED);

CREATE TABLE `PRODUCT_SOURCE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `PROD_ID` BIGINT NOT NULL,
  `SOURCE_NAME` VARCHAR(200) NOT NULL,
  `POSTAL_CODE` VARCHAR(20) NOT NULL,
  `IS_DEFAULT` VARCHAR(1) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_PROD_SRC_I` ON `PRODUCT_SOURCE` (PROD_ID, POSTAL_CODE);

CREATE TABLE IF NOT EXISTS `RAZORPAY_PAYMENT` (
   `ID` BIGINT NOT NULL AUTO_INCREMENT,
   ORDER_ID BIGINT NOT NULL,
   RAZOR_PAYMENT_ID VARCHAR(50) NOT NULL,
   RAZOR_ORDER_ID VARCHAR(50) NOT NULL,
   RAZOR_SIGNATURE VARCHAR(100) NULL,
   PAYMENT_STATUS VARCHAR(1) NOT NULL,
   AMOUNT DECIMAL(10,2) NOT NULL,
   CURRENCY VARCHAR(3) NOT NULL,
   REASON VARCHAR(50) NOT NULL,
   DESCRIPTION VARCHAR(300) NOT NULL,
   CREATED_BY VARCHAR(200) NOT NULL,
   CREATED_DATE DATETIME NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `PAYMENT_ORDERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  ORDER_REF BIGINT NOT NULL,
  RESULT_STATUS VARCHAR(20) NOT NULL,
  RESULT_CODE VARCHAR(10) NOT NULL,
  RESULT_MSG VARCHAR(300) NOT NULL,
  TXN_ID VARCHAR(100) NULL,
  BANK_TXN_ID VARCHAR(100) NULL,
  TXN_AMOUNT DECIMAL(10,2) NOT NULL,
  CURRENCY VARCHAR(10) NOT NULL,
  TXN_TYPE VARCHAR(20) NULL,
  GATEWAY_NAME VARCHAR(15) NULL,
  BANK_NAME VARCHAR(50) NULL,
  PAYMENT_MODE VARCHAR(10) NULL,
  REFUND_AMOUNT DECIMAL(10,2) NULL,
  TXN_DATE DATETIME NULL,
  SUBS_ID VARCHAR(50) NULL,
  PAYABLE_AMOUNT DECIMAL(10,2) NULL,
  PAYMENT_PROMO VARCHAR(50) NULL,
  TRANSFER_MODE VARCHAR(50) NULL,
  UTR VARCHAR(50) NULL,
  BANK_TXN_DATE DATETIME NULL,
  ORDER_STATUS VARCHAR(1) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_PAY_I` ON `PAYMENT_ORDERS` (ORDER_REF, UPDATED_DATE);

CREATE TABLE IF NOT EXISTS `PAYMENT_CUSTOMER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  VAN_ID BIGINT NOT NULL,
  NAME VARCHAR(100) NULL,
  EMAIL VARCHAR(100) NULL,
  PHONE VARCHAR(20) NULL,
  UDF1 VARCHAR(100) NULL,
  UDF2 VARCHAR(100) NULL,
  UDF3 VARCHAR(100) NULL,
  UDF4 VARCHAR(100) NULL,
  UDF5 VARCHAR(100) NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `SOURCE_ACCOUNT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PAYMENT_ORDER_ID BIGINT NOT NULL,
  MASKED_ACC_NO VARCHAR(100) NULL,
  ACC_HOLDER_NAME VARCHAR(100) NULL,
  IFSC_CODE VARCHAR(30) NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `VIRTUAL_ACCOUNT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PAYMENT_ORDER_ID BIGINT NOT NULL,
  VAN VARCHAR(100) NULL,
  BENEFICIARY_NAME VARCHAR(100) NULL,
  IFSC_CODE VARCHAR(30) NULL,
  BANK_NAME VARCHAR(100) NULL,
  PURPOSE VARCHAR(250) NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `VENDOR` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  VENDOR_CODE VARCHAR(10) NULL,
  VENDOR_NAME VARCHAR(100) NOT NULL,
  COMPANY_NAME VARCHAR(100) NOT NULL,
  MOBILE_NO VARCHAR(15) NOT NULL,
  ALTERNATE_NO VARCHAR (15) NULL,
  EMAIL VARCHAR(40) NULL,
  TELEPHONE VARCHAR(20) NULL,
  ADDRESS VARCHAR(400) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  PIN_CODE VARCHAR(15) NOT NULL,
  GST_NO VARCHAR(25) NOT NULL,
  PAN_NO VARCHAR(20) NULL,
  BANK_ACCOUNT_NO VARCHAR(20) NOT NULL,
  ACC_HOLDER_NAME VARCHAR(50) NULL,
  IFSC_CODE VARCHAR(15) NOT NULL,
  VENDOR_SIGNATURE VARCHAR(500) NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_VEND_I` ON `VENDOR` (VENDOR_NAME, COMPANY_NAME, ACTIVE, DELETED);

CREATE TABLE IF NOT EXISTS `NOTIFICATIONS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  ORDER_REF BIGINT NOT NULL,
  CUSTOMER_NAME VARCHAR(100) NOT NULL,
  MOBILE_NO VARCHAR(15) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  TYPE VARCHAR(1) NOT NULL,
  SENT_BY VARCHAR(200) NOT NULL,
  SENT_DATE DATETIME NOT NULL,
  REFUND DECIMAL(10,2) NULL,
  REASON VARCHAR(50) NULL,
  ORDER_STATUS VARCHAR(1) NOT NULL,
  DELIVERY_DATE DATETIME NULL,
  PRODUCT_ID BIGINT NULL,
  PRODUCT_CODE VARCHAR(20) NULL,
  PRODUCT_NAME VARCHAR(100) NULL,
  ORDER_NO VARCHAR(50) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_NOTIF_I` ON `NOTIFICATIONS` (ORDER_REF, MOBILE_NO);

CREATE TABLE IF NOT EXISTS `SERVICE_CHARGES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  AMOUNT VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(200) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY VARCHAR(200) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  ACTIVE VARCHAR(1) NOT NULL,
  DELETED VARCHAR(1) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `ADDRESS_REF` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  REF BIGINT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `ORDER_REF` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  REF BIGINT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `INVOICE_SETTINGS` (
   `ID` BIGINT NOT NULL AUTO_INCREMENT,
   SEQUENCE_TYPE VARCHAR(10) NOT NULL,
   PREFIX VARCHAR(10) NOT NULL,
   FINANCIAL_YEAR VARCHAR(10) NOT NULL,
   SEQUENCE_NO VARCHAR(30) NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS `INVOICE_PROD_SEQ` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
   INVOICE_PROD_REF VARCHAR(50) NOT NULL,
   VENDOR_ID BIGINT NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;
